version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  app:
    build:
      context: ../
      dockerfile: ./app/Dockerfile
    restart: always
    command: >
      sh -c "python3 main.py"
    depends_on:
      - db
    env_file:
      - ./.env

  bot:
    build:
      context: ../
      dockerfile: ./bot/Dockerfile
    restart: always
    command: >
      sh -c "python3 main.py"
    depends_on:
      - db
    env_file:
      - ./.env


volumes:
  postgres_data:
